#!/bin/sh
YETI_LIBDIR=${YETI_LIBDIR:=../yeti}
if [ ! -d "$YETI_LIBDIR" ]; then 
    YETI_LIBDIR=../other/yeti
fi
rlwrap $JAVA_HOME/bin/java -classpath $YETI_LIBDIR/yeti.jar:$YETI_LIBDIR/yeti-lib.jar:jtransforms-2.4.jar yeti.lang.compiler.yeti "$@"
